### ISSUE TITLE
There is no webpack config in the webpack example

### ISSUE THREAD

**Issue by kerrermanisNL** [Iperity/Compass.js#9]
The webpack example doesn't actually contain a config.

**Comment by nbruning** [comment]
We've added an empty config in d03a56986fd1670f5049484cb072c6dc4debb59c, what more would you like to see in the example?

**Comment by kerrermanisNL** [comment]
I imagined the webpack example would include a webpack config, i.e. not it just contains `{}`. Thought it might be useful to place something more in there since I imagine this won't work of the bat.

**Comment by kerrermanisNL** [comment]
:see_no_evil: Welp, I figured I didn't need the webpack in hindsight. Sorry for the confusion!
